### ISSUE TITLE
Getting "failed to open stream: No such file or directory in /autoload.php on line 5" when loading package

### ISSUE THREAD

**Issue by aaronbushnell** [laminas/laminas-feed#22] opened 2020-09-05 22:54 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.12

#### Summary

I am seeing the following error message when using a stock install via Composer. Here's my composer file.

```json
{
    "name": "test-app",
    "type": "project",
    "require": {
        "laminas/laminas-feed": "^2.12"
    }
}
```

And here is my PHP file that autoloads the Composer dependencies:
```php
<?php

require_once '../vendor/autoload.php';

echo "Hello";
```

I'm seeing this issue in craftcms/cms#6773, but posting it here as it seems to be occurring due to the laminas/laminas-feed package.

#### Current behavior

Instead of echoing "Hello", the browser outputs the following:

```
Warning: require_once(//composer/autoload_real.php): failed to open stream: No such file or directory in /autoload.php on line 5

Fatal error: require_once(): Failed opening required '//composer/autoload_real.php' (include_path='.:/opt/sp/php7.3/lib/php') in /autoload.php on line 5
```

#### How to reproduce

This is a bit tricky because it works locally, but doesn't on a Digital Ocean server. However:

1. Setup a basic composer.json
2. Install `laminas/laminas-feed`
3. Autoload deps

#### Expected behavior

The dependency should load correctly and echo my "Hello" text.

**Comment by Ocramius** [comment] 2020-09-06 11:30
What happens if you run `composer dump-autoload` and retry? Same result?

**Comment by aaronbushnell** [comment] 2020-09-06 12:02
Same thing, unfortunately! It's very strange. It works just fine locally, but running this on a Digital Ocean box is giving me this particular issue. Both on the exact same version of Composer, too:

```
   ______
  / ____/___  ____ ___  ____  ____  ________  _____
 / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
                    /_/
Composer version 1.8.0 2018-12-03 10:31:16
```

**Comment by weierophinney** [comment] 2020-09-11 13:49
I think I found the issue: your Composer version. That's an old one (current versions are 1.10+), and we've occassionally seen issues in the Composer Plugin API with older versions. Run `composer self-update`, then blow away your `composer.lock` file and `vendor/` directory, and run `composer install` and see if that corrects the issue. If so, we can document that further.

(I've also commented on the original issue on craftcms.)

**Comment by aaronbushnell** [comment] 2020-09-11 14:20
@weierophinney Unfortunately it doesn't appear to be my Composer version. I [ran through a handful of tests](https://github.com/craftcms/cms/issues/6773#issuecomment-691122096) in the Craft CMS issue and this happens even on Composer 1.10.10. Happy to help debug/diagnose this further!

**Comment by froschdesign** [comment] 2020-09-19 11:01
The problem is unrelated to this component and the original problem is fixed with https://github.com/laminas/laminas-zendframework-bridge/pull/71.

**Closed as completed by froschdesign** 2020-09-19 11:01 UTC
